# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000

server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd800881
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false  # 显示SQL语句
    properties:
      hibernate:
        format_sql: false  # 显示SQL语句
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jmx:
    enabled: false

  # Mail server properties
  mail:
    host: smtp.sdu.edu.cn
    port: 25
    username: xqli@sdu.edu.cn
    password: 111
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

attach:
  folder: /teach/run/

logging:
  config: classpath:loggback.xml
  level:
    org:
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: ERROR